### PR TITLE
add Cargo.lock file

### PR DESCRIPTION
**Pull request by jecaro**
Please consider adding the `Cargo.lock` file as recommended in the [Cargo Book](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

I'd also like to package this tool for [NixOS](https://nixos.org/) and this file is needed as well for better reproducibility. More info about this [here](https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo).

### CODE REVIEW

**Comment by andrewshadura** [comment]
I see why people might like `Cargo.lock` and similar things, but I actually want users to receive fixes in the updates of inputplug dependencies as long as they don’t break compatibility. If some breakage sneaks in, I’d be happy to update the constraints, but I don’t want to lock users to a single set of dependencies.

**Comment by andrewshadura** [comment]
In any case, thanks for your contribution, even though I decided not to merge it, I’m happy you’re interested in inputplug.

**Comment by jecaro** [comment]
Ok np. I can workaround without it for the packaging.

I'll add myself as the maintainer of the NixOS package. Would you be interested to be added as well ?

**Comment by andrewshadura** [comment]
I don’t use NixOS or know how stuff is packaged for it, so I’m not sure how much useful it would be 🙂

**Comment by jecaro** [comment]
Ok. I needed to ask. I'll take care of it.

Thx for this great tool :+1:

**Pull request closed without merging**
